[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools >= 61.0",
]

[project]
name = "{{cookiecutter.project_name}}"
version = "0.0.1"
authors = [
  { name = "{{cookiecutter.full_name}}", email = "{{cookiecutter.email}}" },
]
description = "{{cookiecutter.project_short_description}}"
readme = "README.md"
requires-python = ">= 3.14"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development",
  "Typing :: Typed",
]
dependencies = [
]

[project.urls]
"Homepage" = "https://github.com/{{cookiecutter.organization_name}}/{{cookiecutter.project_name}}"
"Bug Tracker" = "https://github.com/{{cookiecutter.organization_name}}/{{cookiecutter.project_name}}/issues"
"Source" = "https://github.com/{{cookiecutter.organization_name}}/{{cookiecutter.project_name}}"
"Documentation" = "https://{{cookiecutter.organization_name}}.github.io/{{cookiecutter.project_name}}"
"Changelog" = "https://github.com/{{cookiecutter.organization_name}}/{{cookiecutter.project_name}}/releases"

[project.optional-dependencies]
dev = [
  "coverage[toml]",
  "mkdocs",
  "ruff",
  "ty",
]
stage = [
  "build",
  "coverage[toml]",
  "mkdocs",
  "python-docs-generator @ git+https://github.com/jhunufernandes/python-docs-generator",
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "def _",
]

[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = [
  "ALL",
]
ignore = [
  "ANN401",  # any-type
  "ANN003",  # missing-type-kwargs
  "ANN002",  # missing-type-args
  "TID252",  # relative-imports
]

[tool.ruff.lint.pydocstyle]
convention = "google"
