name: tests
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
jobs:
  install-deps:
    uses: jhunufernandes/python-github-actions/.github/workflows/deps.yml@main
    with:
      extras: tests
  run-tests:
    needs:
      - install-deps
    uses: jhunufernandes/python-github-actions/.github/workflows/tests.yml@main
    with:
      extras: tests
